#!/bin/bash

source "$CONFIG_DIR/icons.sh"  # Loads all defined icons
source "$CONFIG_DIR/colors.sh" # Loads all defined colors

export PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
PADDINGS=3

export FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
# export FONT="sketchy-app-font"

bar=(
  height=40
  color="$TRANSPARENT"
  border_width=2
  border_color="$TRANSPARENT"
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=0
  margin=-2
  topmost=window
)
sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color="$ICON_COLOR"
  icon.padding_left="$PADDINGS"
  icon.padding_right="$PADDINGS"
  label.font="$FONT:Semibold:13.0"
  label.color="$LABEL_COLOR"
  label.padding_left="$PADDINGS"
  label.padding_right="$PADDINGS"
  padding_right="$PADDINGS"
  padding_left="$PADDINGS"
  background.height=30
  background.corner_radius=18
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color="$POPUP_BORDER_COLOR"
  popup.background.color="$POPUP_BACKGROUND_COLOR"
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=off
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/front_app.sh"


# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/sound.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/statuses.sh"
source "$ITEM_DIR/music.sh"


sketchybar --hotload true

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
