#!/bin/bash
# shellcheck disable=SC1091

source "$CONFIG_DIR/icons.sh"
source "$CONFIG_DIR/colors.sh"

export PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
export FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants

bar=(
  height=44
  color="$TRANSPARENT"
  border_width=0
  border_color="$TRANSPARENT"
  shadow=off
  position=top
  sticky=on
  padding_right=5
  padding_left=5
  y_offset=0
  margin=8
  topmost=off
)
sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color="$ICON_COLOR"
  icon.padding_left=4
  icon.padding_right=4
  label.font="$FONT:Semibold:13.0"
  label.color="$LABEL_COLOR"
  label.padding_left=4
  label.padding_right=4
  padding_right=2
  padding_left=2
  background.height=28
  background.corner_radius=8
  background.border_width=0
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color="$POPUP_BORDER_COLOR"
  popup.background.color="$POPUP_BACKGROUND_COLOR"
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=off
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/sound.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/statuses.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/music.sh"

sketchybar --hotload true

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
